inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  SuggestExtensions: false

Metrics/MethodLength:
  Enabled: true
  Max: 10
  CountComments: false
